# Generated by Django 5.2.5 on 2026-01-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conference", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "مدير النظام"),
                    ("organizer", "منظم المؤتمر"),
                    ("speaker", "متحدث"),
                    ("attendee", "مشارك"),
                ],
                default="attendee",
                max_length=20,
            ),
        ),
    ]
